/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import classes.Pesquisa;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno
 */
public class Aplicacao extends javax.swing.JFrame {
    private Pesquisa pesquisa;
    
    public Aplicacao() {
        initComponents();
        setLocationRelativeTo(null);
        pesquisa = new Pesquisa();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuItemCadastrar = new javax.swing.JMenu();
        jMenuItemCadastrarOpiniao = new javax.swing.JMenuItem();
        jMenuListar = new javax.swing.JMenu();
        jMenuItemListarResultado = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pesquisa de opiniões");

        jMenuItemCadastrar.setMnemonic('C');
        jMenuItemCadastrar.setText("Cadastrar");

        jMenuItemCadastrarOpiniao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemCadastrarOpiniao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Profile.png"))); // NOI18N
        jMenuItemCadastrarOpiniao.setText("Opinião");
        jMenuItemCadastrarOpiniao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastrarOpiniaoActionPerformed(evt);
            }
        });
        jMenuItemCadastrar.add(jMenuItemCadastrarOpiniao);

        jMenuBar1.add(jMenuItemCadastrar);

        jMenuListar.setMnemonic('L');
        jMenuListar.setText("Listar");

        jMenuItemListarResultado.setText("Resultado");
        jMenuItemListarResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListarResultadoActionPerformed(evt);
            }
        });
        jMenuListar.add(jMenuItemListarResultado);

        jMenuBar1.add(jMenuListar);

        jMenu3.setText("Opções");

        jMenuItemSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/cancel.png"))); // NOI18N
        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemSair);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemListarResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListarResultadoActionPerformed
        JOptionPane.showMessageDialog(this, pesquisa.dados(), "Saida", 1);
    }//GEN-LAST:event_jMenuItemListarResultadoActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemCadastrarOpiniaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastrarOpiniaoActionPerformed
        TelaPesquisa telaPesquisa = new TelaPesquisa(this,true, pesquisa);
        telaPesquisa.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastrarOpiniaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aplicacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aplicacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aplicacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aplicacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aplicacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuItemCadastrar;
    private javax.swing.JMenuItem jMenuItemCadastrarOpiniao;
    private javax.swing.JMenuItem jMenuItemListarResultado;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenu jMenuListar;
    // End of variables declaration//GEN-END:variables
}
